language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t frankdaza2/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true frankdaza2/react-test npm test

after_success:
  - docker build -t frankdaza2/multi-client ./client
  - docker build -t frankdaza2/multi-nginx ./nginx
  - docker build -t frankdaza2/multi-server ./server
  - docker build -t frankdaza2/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # Take those images and push them to docker hub
  - docker push frankdaza2/multi-client
  - docker push frankdaza2/multi-nginx
  - docker push frankdaza2/multi-server
  - docker push frankdaza2/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket-name: elasticbeanstalk-us-east-2-877403824238
  bucket-path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
